// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgeW9H0NnhIG6847FByOVZ4Q3OZ6bxlWQ',
    appId: '1:832213740679:web:b310cb6cb429e3b5ab5c22',
    messagingSenderId: '832213740679',
    projectId: 'ai-adventurer-makina',
    authDomain: 'ai-adventurer-makina.firebaseapp.com',
    storageBucket: 'ai-adventurer-makina.firebasestorage.app',
    measurementId: 'G-CD3PJ107J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_mtIFMhSXB20IC162R_osOiRRfkbFvY',
    appId: '1:832213740679:android:ed65625da446ecfcab5c22',
    messagingSenderId: '832213740679',
    projectId: 'ai-adventurer-makina',
    storageBucket: 'ai-adventurer-makina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCexZI3XCAIpv60_KpIAg6wBykXgjTr5U',
    appId: '1:832213740679:ios:ce290524c0438510ab5c22',
    messagingSenderId: '832213740679',
    projectId: 'ai-adventurer-makina',
    storageBucket: 'ai-adventurer-makina.firebasestorage.app',
    iosBundleId: 'com.example.aiAdventurerMakina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCexZI3XCAIpv60_KpIAg6wBykXgjTr5U',
    appId: '1:832213740679:ios:ce290524c0438510ab5c22',
    messagingSenderId: '832213740679',
    projectId: 'ai-adventurer-makina',
    storageBucket: 'ai-adventurer-makina.firebasestorage.app',
    iosBundleId: 'com.example.aiAdventurerMakina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgeW9H0NnhIG6847FByOVZ4Q3OZ6bxlWQ',
    appId: '1:832213740679:web:5cc03bb3d5455f20ab5c22',
    messagingSenderId: '832213740679',
    projectId: 'ai-adventurer-makina',
    authDomain: 'ai-adventurer-makina.firebaseapp.com',
    storageBucket: 'ai-adventurer-makina.firebasestorage.app',
    measurementId: 'G-BY739GMLMK',
  );

}